# Generated by Django 6.0.6 on 2026-06-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nazwa')),
                ('identifier', models.CharField(help_text='Unikalny numer / oznaczenie zwierzęcia.', max_length=50, unique=True, verbose_name='Identyfikator')),
                ('sex', models.CharField(choices=[('F', 'Samica'), ('M', 'Samiec'), ('U', 'Nieznana')], default='U', max_length=1, verbose_name='Płeć')),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Zdrowe'), ('TREATMENT', 'W trakcie leczenia'), ('SICK', 'Chore')], default='HEALTHY', max_length=20, verbose_name='Stan zdrowia')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data urodzenia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Zwierzę',
                'verbose_name_plural': 'Zwierzęta',
                'ordering': ['name', 'identifier'],
            },
        ),
        migrations.CreateModel(
            name='AnimalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Treść notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Notatka zwierzęcia',
                'verbose_name_plural': 'Notatki zwierzęcia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa gatunku')),
            ],
            options={
                'verbose_name': 'Gatunek',
                'verbose_name_plural': 'Gatunki',
                'ordering': ['name'],
            },
        ),
    ]
