# Generated by Django 6.0.6 on 2026-06-13 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='buildings.building', verbose_name='Lokalizacja'),
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='animals.species', verbose_name='Gatunek'),
        ),
    ]
