# Generated by Django 6.0.6 on 2026-06-13 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_seed_species'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='notes',
        ),
        migrations.CreateModel(
            name='AnimalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Treść notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data aktualizacji')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_history', to='animals.animal', verbose_name='Zwierzę')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Notatka zwierzęcia',
                'verbose_name_plural': 'Notatki zwierzęcia',
                'ordering': ['-created_at'],
            },
        ),
    ]
