# Generated by Django 6.0.6 on 2026-06-13 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data przypomnienia')),
                ('message', models.CharField(max_length=255, verbose_name='Treść')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktywne'), ('SENT', 'Wysłane'), ('CANCELLED', 'Anulowane')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name': 'Przypomnienie',
                'verbose_name_plural': 'Przypomnienia',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('category', models.CharField(choices=[('HEALTH', 'Zdrowotne'), ('MANAGEMENT', 'Zarządcze')], default='MANAGEMENT', max_length=20, verbose_name='Kategoria')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Typ zadania',
                'verbose_name_plural': 'Typy zadań',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('status', models.CharField(choices=[('PLANNED', 'Zaplanowane'), ('DONE', 'Wykonane'), ('CANCELLED', 'Anulowane')], default='PLANNED', max_length=20, verbose_name='Status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Termin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='animals.animal', verbose_name='Zwierzę')),
            ],
            options={
                'verbose_name': 'Zadanie',
                'verbose_name_plural': 'Zadania',
                'ordering': ['due_date', '-created_at'],
            },
        ),
    ]
