# Generated by Django 6.0.6 on 2026-06-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('type', models.CharField(choices=[('STABLE', 'Stajnia'), ('STALL', 'Boks'), ('PEN', 'Zagroda'), ('PADDOCK', 'Wybieg')], default='STABLE', max_length=20, verbose_name='Typ lokalizacji')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name': 'Lokalizacja',
                'verbose_name_plural': 'Lokalizacje',
            },
        ),
    ]
