# Generated by Django 6.0.6 on 2026-06-13 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='description',
        ),
        migrations.CreateModel(
            name='BuildingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Treść notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data aktualizacji')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_history', to='buildings.building', verbose_name='Lokalizacja')),
            ],
            options={
                'verbose_name': 'Notatka lokalizacji',
                'verbose_name_plural': 'Notatki lokalizacji',
                'ordering': ['-created_at'],
            },
        ),
    ]
